"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {
    "includes": ["beautifulsoup4", "certifi", "charset-normalizer", "gitdb", "GitPython", "idna", "Pillow", "PySide6",
                 "PySide6-Addons", "PySide6-Essentials", "requests", "selenium", "shiboken6", "smmap", "soupsieve",
                 "urllib3"]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],

)
